check possible fraud to some client
oyurimatheus/nosso-servico-de-pagamento pull request #3
Opened 2020-05-25 17:36 UTC by oyurimatheus

2020-05-25 17:44 UTC, oyurimatheus commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/ListPaymentMethodsController.java
> -        Set<PaymentMethod> paymentsAllowed = restaurantRepository.findPaymentMethodsAllowedTo(restaurantId, user);
Será que vale a pena aqui pegar o cliente completo do banco? Por que, sendo o email o identificador único de um cliente no sistema, será que seria mais fácil carregar esse email e quando preciso trazer um cliente do banco?

2020-05-25 19:49 UTC, asouza requested changes
Refatorar o fluxo de verificação de pagamentos disponíveis para fraudadores. Decidir se vai ser procedural ou se vai pro lado da orientação a objetos. Minha sugestão é dar um passo atrás e ir para o lado de OO

2020-05-29 20:23 UTC, asouza requested changes

2020-05-29 20:23 UTC, asouza commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/ListPaymentMethodsController.java
>          List<Fraud> frauds = fraudCheck.checkClient(client);
Percebe que aqui nesse fluxo você passa o cliente para achar as pessoas que são possíveis fraudadoras e depois chama um método no mesmo cliente passando a lista de fraudes computadas a partir do próprio. 

Uma sugestão é você passar o service como argumento do método paymentMethodsTo . Poderia passar inclusive a lista toda.

2020-05-29 20:23 UTC, asouza commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/User.java
> +                               .filter(method -> !method.payOnline())
Agora aqui é um ponto de interpretação, pelo menos nesse momento. A regra de fraude, na minha interpretação, junta um cliente com a forma de pagamento. Pq o cliente é um fraudador, neste momento, se ele tem email X + pagamento online.  Então, talvez a interface de fraude devesse receber cliente e forma de pagamento.

2020-06-01 10:09 UTC, asouza approved these changes

2020-06-01 16:50 UTC, merged