Listagem rapida para restaurantes favoritos
oyurimatheus/nosso-servico-de-pagamento pull request #4
Opened 2020-06-02 20:56 UTC by oyurimatheus

2020-06-02 22:28 UTC, oyurimatheus commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/ListPaymentMethodsController.java
> +    @Cacheable(value = "paymentMethods", key = "#root.args[1]")
Deixei o cache por requisição usando o email da pessoa como chave. Uma forma que pensei em contar as requisições seria criar um `Interceptor` para isso

2020-06-04 00:27 UTC, oyurimatheus commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/PaymentMethodsFactory.java
> +class PaymentMethodsFactory {
Não gostei muito dessa implementação, mas não consegui pensar em outra forma

2020-06-04 00:37 UTC, oyurimatheus commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/PaymentMethodsFactory.java
> +    public Set<PaymentMethod> getServiceBased(Long restaurantId, String email) {
Eu pensei em isso aqui retornar uma implementação de um serviço de busca que pega ou do cache ou do banco, mas no desenvolvimento achei melhor deixar assim, por enquanto

2020-06-04 00:40 UTC, oyurimatheus commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/PaymentMethodsFactory.java
> +    public Set<PaymentMethod> getPaymentMethods(Long restaurantId, String email) {
Pensei em retornar aqui uma implementação de um serviço no qual um busca do banco ou do cache, dependendo da implementação. Mas durante o desenvolvimento, acabei indo por esse caminho

2020-06-04 09:34 UTC, asouza requested changes

2020-06-04 09:34 UTC, asouza commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/ListPaymentMethodsController.java
> +    @Cacheable(value = "paymentMethods", key = "#root.args[1]")
Opa, realmente não da para ser assim. Pq aí você não controla a quantidade de pedidos de formas de pagamento daquele usuário para aquele restaurante.

2020-06-04 09:34 UTC, asouza commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/ListPaymentMethodsController.java
> +        Set<PaymentMethod> paymentMethodsAllowed = paymentMethodsFactory.getPaymentMethods(restaurantId, email);
*Toda indireção aumenta a dificuldade de entendimento da aplicação como um todo, ela precisa merecer existir. Ou seja, precisa ajudar a distribuir a carga intrínseca pelo sistema.*

Aqui seu código ficou desbalanceado mesmo.  A PaymentMethodsFactory é bem mais dificil de entender do que essa. Minha sugestão é trazer o código dela para essa classe. Quando você trouxer vai dar uns 9 pontos. Como você pode dividir de maneira equilibrada?

2020-06-05 00:17 UTC, oyurimatheus commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/ListPaymentMethodsController.java
> +                                                                                  restaurantRepository,
O Java não tem uma interface funcional que não recebe nenhum parâmetro e retorna algo... Tem a `Runnable`, mas ela retorna `void` . Só queria deixar registrado que fiquei meio triste com isso haha

2020-06-05 00:19 UTC, oyurimatheus commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/ListPaymentMethodsController.java
> +        Set<PaymentMethod> paymentMethods = searchPaymentInCache.findPaymentMethods();
Pensei em implementar aqui algo próximo a um chain, mas mesmo assim, pela minha conta, o controller ficou com 9 pontos de carga...

2020-06-05 09:49 UTC, asouza requested changes

2020-06-05 09:49 UTC, asouza commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/ListPaymentMethodsController.java
> +                                                                                  restaurantRepository,
https://docs.oracle.com/javase/8/docs/api/java/util/function/Supplier.html ?

2020-06-05 09:49 UTC, asouza commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/ListPaymentMethodsController.java
> +        Set<PaymentMethod> paymentMethods = searchPaymentInCache.findPaymentMethods();
É pq aqui cachedUser é um parâmetro e não uma dependência :). Essa aqui ```SearchPaymentMethodsInCache``` poderia ser gerenciada pelo spring com as dependências do userRepository,resturantRepository e fraudsChecking.   

Outra opção é você ter três blocos de códigos... o que procura no cache, o que busca os pagamentos de fato e o que conta +1 na busca do pagamento.

2020-06-05 09:49 UTC, asouza commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/ListPaymentMethodsController.java
> +        cachedUser.updatePaymentMethods(paymentMethods);
o que são essas duas linhas? pq tem duas linhas para fazer uma operação? pq não é algo como ```contadorUsoBuscaPagamentoRestaurante.incrementa(usuario,resturante)```?

2020-06-05 09:49 UTC, asouza commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/SearchPaymentInDatabase.java
> +class SearchPaymentInDatabase implements FindPaymentMethods {
É, aqui você generalizou algo que só tem 2 possibilidads... busca do banco ou retorna do cache.

2020-06-05 13:23 UTC, oyurimatheus commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/ListPaymentMethodsController.java
> +                                                                                  restaurantRepository,
Não conhecia! Nesse ponto eu queria passar a função de busca de um restaurante e de um usuário

2020-06-05 18:59 UTC, yurioliveirazup commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/SearchPaymentInDatabase.java
> +class SearchPaymentInDatabase implements FindPaymentMethods {
Nesse caso não é interessante deixar aberto para outras possibilidades no futuro?

2020-06-05 19:03 UTC, oyurimatheus commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/SearchPaymentInDatabase.java
> +class SearchPaymentInDatabase implements FindPaymentMethods {
Nesse caso não seria necessário deixar aberto né? Se surgir algo novo no futuro, talvez faça sentido generalizar assim, correto?

2020-06-05 19:05 UTC, oyurimatheus commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/ListPaymentMethodsController.java
> +        cachedUser.updatePaymentMethods(paymentMethods);
Eu estou usando essa linha para atualizar o cache sempre que o dado volta do banco

2020-06-05 22:00 UTC, asouza requested changes
ListPaymentsController está com 4 pontos (3 pontos a menos do limite)
SearchPaymentsDatabase está com 4 pontos(3 pontos a menos do limite)
SearchPaymentsMethodInCache está com 5 pontos (2 abaixo)

Dividir demais parece que complicou você... da para juntar coisas aí :).

2020-06-05 22:00 UTC, asouza commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/SearchPaymentMethodsInCache.java
>          if (cachedUser.incrementAndGet() >= 10) {
*Só alteramos estado de referências que criamos. Não mexemos nos objetos alheios. A não ser que esse objeto seja criado para isso, como é o caso de argumentos de métodos de borda mais externa. Estes são, geralmente, associados a frameworks.*

Aqui você está alterando a referência do cachedUser :).

2020-06-05 22:00 UTC, asouza commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/PaymentsAvailable.java
>  class PaymentsAvailable {
Onde é usada essa classe?

2020-06-05 22:00 UTC, asouza commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/SearchPaymentMethodsInCache.java
> +        paymentCache.updateCache(cachedUser);
paymentCache e cachedUser são referências que não foi você que criou :).

2020-06-06 16:41 UTC, oyurimatheus commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/SearchPaymentMethodsInCache.java
>          if (cachedUser.incrementAndGet() >= 10) {
Mas nesse caso a API do cachedUser prevê isso... Será que é melhor que essa classe utilize do ciclo de vida desse objeto?

2020-06-06 16:45 UTC, oyurimatheus commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/PaymentsAvailable.java
>  class PaymentsAvailable {
Eu esqueci de tirar ela. Essa classe eu usei em um método que estava na classe restaurant, mas já tirei ele

2020-06-06 17:05 UTC, oyurimatheus commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/SearchPaymentMethodsInCache.java
> +        paymentCache.updateCache(cachedUser);
`paymentCache` na verdade é um serviço pra encapsular as chamadas para o cache... No caso, ele quem devolve o `cachedUser`, talvez dê pra utilizar todas essas chamadas dentro do serviço

2020-06-06 18:27 UTC, asouza commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/SearchPaymentMethodsInCache.java
>          if (cachedUser.incrementAndGet() >= 10) {
cachedUser é uma classe sua, a fragilidade disso no sistema é grande. Minha recomendação é seguir a restrição e só quem tem visibilidade da primeira referência altera o estado.

2020-06-06 18:28 UTC, asouza commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/SearchPaymentMethodsInCache.java
> +        paymentCache.updateCache(cachedUser);
Você só sabe que ele é um serviço que faz x ou y pq foi você quem criou :).

2020-06-06 23:09 UTC, oyurimatheus commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/ListPaymentMethodsController.java
> +        cachedUser.updatePaymentMethods(paymentMethods);
Mantive essa linha porque não consegui pensar em outra forma de atualizar o cache

2020-06-07 10:12 UTC, asouza approved these changes
Aqui eu acho ok aprovar porque o aprendizado está um pouco mais claro para mim.  Minha visão: entrou um fluxo que não era tão claro para você e desde o começo você tentou dividir as responsabilidades. Numa próxima funcionalidade que não esteja tão clara, não começa dividindo as responsabilidade. Dado que você entendeu o que precisa ser feito, começa escrevendo o código necessário para funcionar. Depois que funcionar o fluxo fica ainda mais claro e aí você entra com a divisão de responsabilidade. Lembra que a gente tem uma maneira lógica de fazer isso agora... Se você deixar tudo no controller e passar de 7 pontos, você já sabe que precisa dividir.

2020-06-07 10:12 UTC, asouza commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/ListPaymentMethodsController.java
> +        paymentCacheService.updateCache(cachedUser);
O que é esse método faz que não poderia ser feito pelo updatePaymentMethods?

2020-06-07 16:35 UTC, oyurimatheus commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/ListPaymentMethodsController.java
> +        paymentCacheService.updateCache(cachedUser);
Ele de fato salva no Redis o cache. o `updatePaymentMethods` é basicamente um setter para atualizar os meios de pagamento no cache

2020-06-09 20:19 UTC, merged