Processando pagamento offline
oyurimatheus/nosso-servico-de-pagamento pull request #5
Opened 2020-06-12 13:45 UTC by oyurimatheus

2020-06-12 13:47 UTC, oyurimatheus commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/purchase/PaymentController.java
> +class PaymentController {
Pela minha conta, aqui deu 11 pontos de carga... 9 no método `pay`e mais 2 nos validators

2020-06-12 21:55 UTC, asouza requested changes

2020-06-12 21:55 UTC, asouza commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/purchase/CreditCardPaymentCheckValidator.java
> +        if (request.isOnline() && !request.hasCreditCardNumber()) {
Bela sacada aqui. O código está ok.. Meu único ponto é: fica sempre atento quando você usa a mesma referência em dois lados da condicional, provavelmente poderia existir um método só.

2020-06-12 21:55 UTC, asouza commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/purchase/Payment.java
> +
O seu comentário na verdade é uma restrição :). 

```
Assert.isTrue(!paymentMethod.equals(PaymentMethod.CREDIT_CARD),"...")
````

Uma dica pública precisa ser relacionado ao comportamento e menos a implementação :). O comentário poderia ser: construtor para criar pagamentos offlines :). 

Especificamente nesse caso, você poderia avaliar deixar os construtores privados e ter métodos estáticos com nomes também: pagamentoOnline e pagamentoOffline :).

2020-06-12 21:55 UTC, asouza commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/purchase/PaymentController.java
> +        binder.addValidators(new PaymentMethodChoseValidator(restaurantRepository, userRepository, fraudChecking),
Aqui você tem objetos de transição. Em vez de receber todos eles, você pode receber o ApplicationContext e mandar um .getBean(PaymentMethodChoseValidator.class) ou receber o próprio PaymentMethodChoseValidator injetado, acho.

2020-06-12 21:55 UTC, asouza commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/purchase/PaymentMethodChoseValidator.java
> +        if (!paymentMethods.contains(request.getPaymentMethod())) {
Código aqui está ok também. Uma alternativa seria ```user.accept(request.getPaymentMethod(),restaurant,fraudChecking)```

2020-06-12 21:55 UTC, asouza commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/purchase/PaymentController.java
> +        HashMap<String, Object> response = new HashMap<>();
Foi ligeiro aqui. abraçou o caos do bem!

2020-06-12 21:55 UTC, asouza commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/purchase/PaymentController.java
> +        PaymentTransaction transactional = paymentProcessor.process(payment);
Aqui é para você ir gerando múltiplas transações para um mesmo payment, não é? tem um detalhe. Uma compra de id X não pode ser gerada offline mais de uma vez :). Eu não coloquei lá,mas é importante implementar.

2020-06-15 22:01 UTC, oyurimatheus commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/purchase/PaymentController.java
> +        binder.addValidators(new PaymentMethodChoseValidator(restaurantRepository, userRepository, fraudChecking),
Não sei se sei fazer isso haha, mas vou dar uma pesquisada

2020-06-15 22:03 UTC, oyurimatheus commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/purchase/PaymentController.java
> +        PaymentTransaction transactional = paymentProcessor.process(payment);
Hmm, faz sentido por conta dos estados do tipo de pagamento também

2020-06-15 22:04 UTC, oyurimatheus commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/purchase/Payment.java
> +
Faz sentido! Acho que método estáticos fazem mais sentido pensando na API pública desse caso

2020-06-16 11:02 UTC, asouza commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/purchase/PaymentController.java
> +        binder.addValidators(new PaymentMethodChoseValidator(restaurantRepository, userRepository, fraudChecking),
Você pode declarar o PaymentMemthodChoseValidator como component e pedir injetado na classe também :). Aí só repassa

2020-06-16 19:38 UTC, oyurimatheus commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/purchase/PaymentController.java
> +        PaymentTransaction transactional = paymentProcessor.process(payment);
Levantei uma exceção caso já exista uma transação para um pagamento offline

2020-06-18 22:12 UTC, asouza approved these changes

2020-06-18 22:12 UTC, asouza commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/purchase/PaymentProcessor.java
> +            verifyTransactionAlreadyExist(payment);
O método privado aqui surgiu por algum motivo especial?

2020-06-19 17:30 UTC, oyurimatheus commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/purchase/PaymentProcessor.java
> +            verifyTransactionAlreadyExist(payment);
Só porque eu acho muito feio muitos `ifs` aninhados haha

2020-06-19 20:18 UTC, merged

2020-06-19 20:19 UTC, asouza commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/purchase/PaymentProcessor.java
> +            verifyTransactionAlreadyExist(payment);
hehehe. Ok :).