Deve atender milhares de requisicoes
oyurimatheus/nosso-servico-de-pagamento pull request #7
Opened 2020-07-23 16:00 UTC by oyurimatheus

2020-07-23 16:55 UTC, oyurimatheus commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/purchase/gateways/PaymentGatewayClient.java
> +    boolean payAsync(URI baseUri, PaymentGatewayRequest request) {
Acho que aqui a melhor coisa é retornar um `CompletableFuture` né?

2020-07-30 10:54 UTC, asouza requested changes

2020-07-30 10:54 UTC, asouza commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/list/ListPaymentMethodsController.java
> +            return ok().header("Cache-Control", "private", "max-age=14400").body(response);
Boa aqui. Lembra que o tempo do cache é um requisito de negócio e a gente deve sempre falar com as pessoas que direcionam o produto.

2020-07-30 10:54 UTC, asouza commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/purchase/gateways/PaymentGatewayClient.java
> +        RequestConfig config = RequestConfig.custom()
Caso essa configuração seja reaproveitada, você pode criar um método de fábrica para ela. E já deixa também os valores vindo do properties? 

Também talvez valha a pena você brincar com o feign aqui :). 

De toda forma é isso, setar timeout é super importante! Tem que ter, inclusive para as queries do banco de dados!

2020-07-30 10:54 UTC, asouza commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/purchase/gateways/PaymentGatewayClient.java
> +        try {
E aí para cada retorno você guarda a falha, é isso?

2020-07-31 13:39 UTC, oyurimatheus commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/list/ListPaymentMethodsController.java
> +            return ok().header("Cache-Control", "private", "max-age=14400").body(response);
Eu coloquei o mesmo valor de expiração do cache que existe no Redis, mas eu não lembro se eu perguntei para você a validade mesmo

2020-07-31 13:40 UTC, oyurimatheus commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/purchase/gateways/PaymentGatewayClient.java
> +        try {
Isso, qualquer retorno diferente de 2xx, é lançada uma exceção. Nesse caso eu faço um log da exceção e retorno `false` para indicar que aquele serviço não respondeu como esperado

2020-07-31 13:44 UTC, oyurimatheus commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/purchase/gateways/PaymentGatewayClient.java
> +        RequestConfig config = RequestConfig.custom()
Eu comecei usando o Feign na primeira versão do código, mas mudei por algum motivo que não estou lembrado. A ideia do método de fábrica é bem legal!

2020-07-31 15:00 UTC, asouza approved these changes

2020-07-31 15:00 UTC, asouza commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/list/ListPaymentMethodsController.java
> +            return ok().header("Cache-Control", "private", String.format("max-age=%d", DEFAULT_CACHE_TIME)).body(response);
Todas essas configurações você pode deixar no application.properties :).

2020-07-31 15:00 UTC, asouza commented on src/main/java/me/oyurimatheus/nossoservicodepagamento/payment/purchase/gateways/PaymentGatewayClientFactory.java
> +    public RestTemplate getRestTemplate() {
Boa! Se você quisesse que essa fosse a configuraçao padrão poderia inclusive marcar o método com @Bean. Se quisesse que fosse específico, poderia marcar com @Bean e fornece um nome específico.

2020-08-04 21:51 UTC, merged